
project_id = "xojrleypudfrbmvejpow"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "fortnox-token-exchange"
verify_jwt = false

[[functions]]
name = "fortnox-token-migration"
verify_jwt = false

[[functions]]
name = "fortnox-token-refresh"
verify_jwt = false
