
project_id = "xojrleypudfrbmvejpow"

[functions.get-all-users]
verify_jwt = true

[functions.fortnox-proxy]
verify_jwt = false

[functions.fortnox-token-exchange]
verify_jwt = false

[functions.fortnox-token-refresh]
verify_jwt = false

[functions.fortnox-token-migrate]
verify_jwt = false
