
project_id = "xojrleypudfrbmvejpow"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.fortnox-scheduled-refresh]
verify_jwt = false

[functions.fortnox-token-exchange]
verify_jwt = false

[functions.fortnox-token-refresh]
verify_jwt = false

[functions.fortnox-token-migrate]
verify_jwt = false

[functions.fortnox-token-debug]
verify_jwt = false

[functions.fortnox-proxy]
verify_jwt = false

[functions.db-connection-test]
verify_jwt = false

[functions.test-database-connection]
verify_jwt = false

[functions.get-all-users]
verify_jwt = false

