
# The project ID for your application on Supabase
project_id = "xojrleypudfrbmvejpow"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[realtime]
enabled = true

[functions]
[functions.fortnox-token-exchange]
verify_jwt = false

[functions.fortnox-scheduled-refresh]
verify_jwt = false

[functions.fortnox-token-refresh]
verify_jwt = false

[functions.fortnox-token-migrate]
verify_jwt = false

[functions.fortnox-proxy]
verify_jwt = false

[functions.get-all-users]
verify_jwt = true

[functions.fortnox-token-debug]
verify_jwt = false
